<a href="https://colab.research.google.com/github/MisGall10/Practica_4_Misael_Gallardo/blob/main/Practica4MAGC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practica # 4. Manipulación de matrices**

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:

1. Suma ambas matrices.
2. Resta la segunda matriz de la primera.
3. Multiplica la primera matriz por 2.
4. Realiza una multiplicación matricial entre las dos matrices.

In [13]:
#Importamos numpy y la nombramos como np
import numpy as np
#Creamos la matriz A con ayuda de np.random.randit
A = np.random.randint(1,11,(3,3))
#Creamos la matriz B con ayuda de np.random.randit
B = np.random.randint(1,11,(3,3))
#Imprimimos el valor de la matriz A
print(f'La matriz A es: \n{A}')
#Imprimimos el valor de la matriz B
print(f'La matriz B es: \n{B}')
#Imprimimos el valor de A + B
print(f'1. La operacion de la matriz A + B es: \n{A + B}')
#Imprimimos el valor de B - A
print(f'2. La operacion de la matriz B - A es: \n{B - A}')
#Imprimimos el valor de 2A
print(f'3. La operacion de la matriz 2A es: \n{A * 2}')
#Imprimimos el valor de A x B
print(f'4. La operacion de la matriz AxB es: \n{np.dot(A,B)}')

La matriz A es: 
[[ 8  5  6]
 [ 9  5  7]
 [10  6  3]]
La matriz B es: 
[[ 5 10  4]
 [ 9  7  2]
 [ 7  5  1]]
1. La operacion de la matriz A + B es: 
[[13 15 10]
 [18 12  9]
 [17 11  4]]
2. La operacion de la matriz B - A es: 
[[-3  5 -2]
 [ 0  2 -5]
 [-3 -1 -2]]
3. La operacion de la matriz 2A es: 
[[16 10 12]
 [18 10 14]
 [20 12  6]]
4. La operacion de la matriz AxB es: 
[[127 145  48]
 [139 160  53]
 [125 157  55]]
